---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-spring-boot-k8s
  namespace: jenkins
  labels:
    app: jenkins-sb-k8-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-sb-k8-app
  template:
    metadata:
      name: spring-boot-pod
      labels:
        app: jenkins-sb-k8-app
    spec:
      containers:
      - name: spring-boot-container
        image: venu1322/jenkins-docker-springboot-helloworld-app:V1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata: 
  name: jenkins-spring-boot-k8s
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins-sb-k8-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008